-- Best-effort Snowflake DDL and load SQL generated from [Sample Mapping.xlsx](Sample Mapping.xlsx)
-- Assumptions are documented inline because the mapping document is incomplete/inconsistent.
-- Security note: tasks below do not bind any network services and contain no hardcoded secrets.

USE ROLE SYSADMIN;
USE WAREHOUSE COMPUTE_WH;

CREATE DATABASE IF NOT EXISTS DEV_IBM_DB;
CREATE SCHEMA IF NOT EXISTS DEV_IBM_DB.CURATED;
CREATE SCHEMA IF NOT EXISTS DEV_IBM_DB."FRAMEWORK";
CREATE SEQUENCE IF NOT EXISTS DEV_IBM_DB."FRAMEWORK"."SEQ_CURATE"
    START = 1
    INCREMENT = 1;

USE DATABASE DEV_IBM_DB;
USE SCHEMA CURATED;

-- =====================================================================================
-- ASSUMPTIONS
-- =====================================================================================
-- 1. Target transient tables are created in DEV_IBM_DB.CURATED.
-- 2. Source objects exist and are readable:
--    - DEV_IBM_DB.STAGE.ACCOUNT A
--    - DEV_IBM_DB.RAW.C_SPEC_NOTE SN
--    - DEV_IBM_DB.RAW.VW_CD_ROW_STAT VCRS
--    - PROD_CDP_DB.RAW.VW_CD_SPEC_NOTE CD
-- 3. ACCOUNT_DETAIL_CODE_KEY is generated from DEV_IBM_DB."FRAMEWORK"."SEQ_CURATE".NEXTVAL
--    because the mapping document marks it as a surrogate key but does not provide logic.
-- 4. ACCOUNT_DETAIL load joins SN to A on SN.KY_BA = A.ACCOUNT_KEY as a best-effort assumption
--    because the mapping document references both objects but does not define the join.
-- 5. ACCOUNT_DETAIL load joins VCRS on SN.CD_STAT = VCRS.CD_STAT as a best-effort assumption
--    because only the status source column name is provided.
-- 6. ACCOUNT_DETAIL_CODE uses DISTINCT CD.CODE / CD.DESCRIPTION from RAW.C_SPEC_NOTE SN joined to
--    PROD_CDP_DB.RAW.VW_CD_SPEC_NOTE CD on SN.CD_SPEC_NOTE = CD.CODE filtered by SN.KY_BA <> 0,
--    based on the three split mapping rows.
-- 7. Views are simple projection views over the transient tables.
-- 8. Tasks use a warehouse schedule and execute INSERT ... SELECT as requested.
-- 9. To avoid duplicate re-inserts from a schedule, each task truncates the transient table before load.
--    If append-only history is required, remove the TRUNCATE and add deduplication logic.

-- =====================================================================================
-- TRANSIENT TARGET TABLE DDL
-- =====================================================================================

CREATE OR REPLACE TRANSIENT TABLE DEV_IBM_DB.CURATED.ACCOUNT_DETAIL (
    ACCOUNT_DETAIL_KEY NUMBER(38,0),
    ACCOUNT_KEY NUMBER(38,0),
    ACCOUNT_DETAIL_CODE_KEY NUMBER(38,0),
    ACCOUNT_DETAIL_STATUS_DESC VARCHAR(254),
    SOURCE_IDENTITY_TXT VARCHAR(254),
    SOURCE_SYS_CD VARCHAR(10),
    SOURCE_SYS_CREATE_DT TIMESTAMP_TZ,
    SOURCE_SYS_MODIFY_DT TIMESTAMP_TZ,
    IUDL_CD VARCHAR(10),
    CREATE_DTTM TIMESTAMP_TZ,
    CREATE_BY_ID VARCHAR(50),
    UPDATE_DTTM TIMESTAMP_TZ,
    UPDATE_BY_ID VARCHAR(50)
);

CREATE OR REPLACE TRANSIENT TABLE DEV_IBM_DB.CURATED.ACCOUNT_DETAIL_CODE (
    ACCOUNT_DETAIL_CODE_KEY NUMBER(38,0),
    ACCOUNT_DETAIL_CD VARCHAR(254),
    ACCOUNT_DETAIL_CODE_DESC VARCHAR(500),
    CREATE_BY_ID VARCHAR(50),
    UPDATE_BY_ID VARCHAR(50),
    CREATE_DTTM TIMESTAMP_TZ,
    UPDATE_DTTM TIMESTAMP_TZ
);

-- =====================================================================================
-- LOAD SQL
-- =====================================================================================

CREATE OR REPLACE TEMPORARY VIEW DEV_IBM_DB.CURATED.V_ACCOUNT_DETAIL_LOAD_SRC AS
SELECT
    DEV_IBM_DB."FRAMEWORK"."SEQ_CURATE".NEXTVAL AS ACCOUNT_DETAIL_KEY,
    A.ACCOUNT_KEY AS ACCOUNT_KEY,
    ADC.ACCOUNT_DETAIL_CODE_KEY AS ACCOUNT_DETAIL_CODE_KEY,
    VCRS.DESCRIPTION AS ACCOUNT_DETAIL_STATUS_DESC,
    SN.KY_BA AS SOURCE_IDENTITY_TXT,
    'IBM' AS SOURCE_SYS_CD,
    COALESCE(NULLIF(SN.CREATE_TIMESTAMP, ''), SN.DT_STAT) AS SOURCE_SYS_CREATE_DT,
    SN.DT_STAT AS SOURCE_SYS_MODIFY_DT,
    'I' AS IUDL_CD,
    CURRENT_TIMESTAMP() AS CREATE_DTTM,
    CURRENT_USER() AS CREATE_BY_ID,
    CURRENT_TIMESTAMP() AS UPDATE_DTTM,
    CURRENT_USER() AS UPDATE_BY_ID
FROM DEV_IBM_DB.STAGE.ACCOUNT A
INNER JOIN DEV_IBM_DB.RAW.C_SPEC_NOTE SN
    ON SN.KY_BA = A.ACCOUNT_KEY
LEFT JOIN DEV_IBM_DB.RAW.VW_CD_ROW_STAT VCRS
    ON SN.CD_STAT = VCRS.CD_STAT
LEFT JOIN DEV_IBM_DB.CURATED.ACCOUNT_DETAIL_CODE ADC
    ON SN.CD_SPEC_NOTE = ADC.ACCOUNT_DETAIL_CD;

INSERT INTO DEV_IBM_DB.CURATED.ACCOUNT_DETAIL (
    ACCOUNT_DETAIL_KEY,
    ACCOUNT_KEY,
    ACCOUNT_DETAIL_CODE_KEY,
    ACCOUNT_DETAIL_STATUS_DESC,
    SOURCE_IDENTITY_TXT,
    SOURCE_SYS_CD,
    SOURCE_SYS_CREATE_DT,
    SOURCE_SYS_MODIFY_DT,
    IUDL_CD,
    CREATE_DTTM,
    CREATE_BY_ID,
    UPDATE_DTTM,
    UPDATE_BY_ID
)
SELECT
    ACCOUNT_DETAIL_KEY,
    ACCOUNT_KEY,
    ACCOUNT_DETAIL_CODE_KEY,
    ACCOUNT_DETAIL_STATUS_DESC,
    SOURCE_IDENTITY_TXT,
    SOURCE_SYS_CD,
    SOURCE_SYS_CREATE_DT,
    SOURCE_SYS_MODIFY_DT,
    IUDL_CD,
    CREATE_DTTM,
    CREATE_BY_ID,
    UPDATE_DTTM,
    UPDATE_BY_ID
FROM DEV_IBM_DB.CURATED.V_ACCOUNT_DETAIL_LOAD_SRC;

INSERT INTO DEV_IBM_DB.CURATED.ACCOUNT_DETAIL_CODE (
    ACCOUNT_DETAIL_CODE_KEY,
    ACCOUNT_DETAIL_CD,
    ACCOUNT_DETAIL_CODE_DESC,
    CREATE_BY_ID,
    UPDATE_BY_ID,
    CREATE_DTTM,
    UPDATE_DTTM
)
SELECT DISTINCT
    DEV_IBM_DB."FRAMEWORK"."SEQ_CURATE".NEXTVAL AS ACCOUNT_DETAIL_CODE_KEY,
    CD.CODE AS ACCOUNT_DETAIL_CD,
    CD.DESCRIPTION AS ACCOUNT_DETAIL_CODE_DESC,
    CURRENT_USER() AS CREATE_BY_ID,
    CURRENT_USER() AS UPDATE_BY_ID,
    CURRENT_TIMESTAMP() AS CREATE_DTTM,
    CURRENT_TIMESTAMP() AS UPDATE_DTTM
FROM DEV_IBM_DB.RAW.C_SPEC_NOTE SN
INNER JOIN PROD_CDP_DB.RAW.VW_CD_SPEC_NOTE CD
    ON SN.CD_SPEC_NOTE = CD.CODE
WHERE SN.KY_BA <> 0;

-- =====================================================================================
-- VIEWS ON TRANSIENT TARGET TABLES
-- =====================================================================================

CREATE OR REPLACE VIEW DEV_IBM_DB.CURATED.VW_ACCOUNT_DETAIL AS
SELECT
    ACCOUNT_DETAIL_KEY,
    ACCOUNT_KEY,
    ACCOUNT_DETAIL_CODE_KEY,
    ACCOUNT_DETAIL_STATUS_DESC,
    SOURCE_IDENTITY_TXT,
    SOURCE_SYS_CD,
    SOURCE_SYS_CREATE_DT,
    SOURCE_SYS_MODIFY_DT,
    IUDL_CD,
    CREATE_DTTM,
    CREATE_BY_ID,
    UPDATE_DTTM,
    UPDATE_BY_ID
FROM DEV_IBM_DB.CURATED.ACCOUNT_DETAIL;

CREATE OR REPLACE VIEW DEV_IBM_DB.CURATED.VW_ACCOUNT_DETAIL_CODE AS
SELECT
    ACCOUNT_DETAIL_CODE_KEY,
    ACCOUNT_DETAIL_CD,
    ACCOUNT_DETAIL_CODE_DESC,
    CREATE_BY_ID,
    UPDATE_BY_ID,
    CREATE_DTTM,
    UPDATE_DTTM
FROM DEV_IBM_DB.CURATED.ACCOUNT_DETAIL_CODE;

-- =====================================================================================
-- TASKS TO SCHEDULE INSERT LOADS
-- =====================================================================================

CREATE OR REPLACE TASK DEV_IBM_DB.CURATED.TASK_LOAD_ACCOUNT_DETAIL_CODE
    WAREHOUSE = COMPUTE_WH
    SCHEDULE = 'USING CRON 0 * * * * UTC'
AS
BEGIN
    TRUNCATE TABLE DEV_IBM_DB.CURATED.ACCOUNT_DETAIL_CODE;

    INSERT INTO DEV_IBM_DB.CURATED.ACCOUNT_DETAIL_CODE (
        ACCOUNT_DETAIL_CODE_KEY,
        ACCOUNT_DETAIL_CD,
        ACCOUNT_DETAIL_CODE_DESC,
        CREATE_BY_ID,
        UPDATE_BY_ID,
        CREATE_DTTM,
        UPDATE_DTTM
    )
    SELECT DISTINCT
        DEV_IBM_DB."FRAMEWORK"."SEQ_CURATE".NEXTVAL,
        CD.CODE,
        CD.DESCRIPTION,
        CURRENT_USER(),
        CURRENT_USER(),
        CURRENT_TIMESTAMP(),
        CURRENT_TIMESTAMP()
    FROM DEV_IBM_DB.RAW.C_SPEC_NOTE SN
    INNER JOIN PROD_CDP_DB.RAW.VW_CD_SPEC_NOTE CD
        ON SN.CD_SPEC_NOTE = CD.CODE
    WHERE SN.KY_BA <> 0;
END;

CREATE OR REPLACE TASK DEV_IBM_DB.CURATED.TASK_LOAD_ACCOUNT_DETAIL
    WAREHOUSE = COMPUTE_WH
    SCHEDULE = 'USING CRON 15 * * * * UTC'
    AFTER DEV_IBM_DB.CURATED.TASK_LOAD_ACCOUNT_DETAIL_CODE
AS
BEGIN
    TRUNCATE TABLE DEV_IBM_DB.CURATED.ACCOUNT_DETAIL;

    INSERT INTO DEV_IBM_DB.CURATED.ACCOUNT_DETAIL (
        ACCOUNT_DETAIL_KEY,
        ACCOUNT_KEY,
        ACCOUNT_DETAIL_CODE_KEY,
        ACCOUNT_DETAIL_STATUS_DESC,
        SOURCE_IDENTITY_TXT,
        SOURCE_SYS_CD,
        SOURCE_SYS_CREATE_DT,
        SOURCE_SYS_MODIFY_DT,
        IUDL_CD,
        CREATE_DTTM,
        CREATE_BY_ID,
        UPDATE_DTTM,
        UPDATE_BY_ID
    )
    SELECT
        DEV_IBM_DB."FRAMEWORK"."SEQ_CURATE".NEXTVAL,
        A.ACCOUNT_KEY,
        ADC.ACCOUNT_DETAIL_CODE_KEY,
        VCRS.DESCRIPTION,
        SN.KY_BA,
        'IBM',
        COALESCE(NULLIF(SN.CREATE_TIMESTAMP, ''), SN.DT_STAT),
        SN.DT_STAT,
        'I',
        CURRENT_TIMESTAMP(),
        CURRENT_USER(),
        CURRENT_TIMESTAMP(),
        CURRENT_USER()
    FROM DEV_IBM_DB.STAGE.ACCOUNT A
    INNER JOIN DEV_IBM_DB.RAW.C_SPEC_NOTE SN
        ON SN.KY_BA = A.ACCOUNT_KEY
    LEFT JOIN DEV_IBM_DB.RAW.VW_CD_ROW_STAT VCRS
        ON SN.CD_STAT = VCRS.CD_STAT
    LEFT JOIN DEV_IBM_DB.CURATED.ACCOUNT_DETAIL_CODE ADC
        ON SN.CD_SPEC_NOTE = ADC.ACCOUNT_DETAIL_CD;
END;

-- Enable tasks explicitly after validation.
-- ALTER TASK DEV_IBM_DB.CURATED.TASK_LOAD_ACCOUNT_DETAIL_CODE RESUME;
-- ALTER TASK DEV_IBM_DB.CURATED.TASK_LOAD_ACCOUNT_DETAIL RESUME;